swagger: '2.0'
info:
  version: "1.4.0"
  title: sampleApi_nestedArrays
  description: "Example of API that contains inputs of primitive types (Double, String, Integer, boolean, array of string, array of double)
  in all the possible sources, excepting the body (query, path, header, form)"
host: es.us.isa
basePath: /sampleApi/v1
schemes:
  - https

securityDefinitions:
  "API Key":
    type: apiKey
    in: header
    name: SAMPLE-API-Key

security:
  - "API Key": []

paths:
  '/primitiveInputsEndpoint/{stringInPath}':
    x-summary: SampleEndpoint
    get:
      summary: Sample endpoint
      operationId: primitiveInputsEndpoint
      description: Get sample results
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/doubleInQuery'
        - $ref: '#/parameters/stringInPath'
        - $ref: '#/parameters/integerInHeader'
        - $ref: '#/parameters/booleanInForm'
        - $ref: '#/parameters/arrayOfString'
        - $ref: '#/parameters/arrayOfDouble'


      responses:
        '200':
          description: "Sample response"
          schema:
            $ref: '#/definitions/supermodelIoLogisticsPUDOLocations'

parameters:

  doubleInQuery:
    name: doubleInQuery
    in: query
    required: true
    type: number # double

  stringInPath:
    name: stringInPath
    in: path
    required: true
    type: string

  integerInHeader:
    name: integerInHeader
    in: header
    required: true
    type: integer # int

  booleanInForm:
    name: booleanInForm
    in: formData
    required: true
    type: boolean

  arrayOfString:
    name: arrayOfString
    in: query
    required: true
    type: array
    items:
      type: string

  arrayOfDouble:
    name: arrayOfDouble
    in: query
    required: true
    type: array
    items:
      type: string

definitions:
  supermodelIoLogisticsPUDOLocations:
    title: Location Collection
    description: DHL Service Point location collection
    type: object
    properties:
      property1:
        type: string
      property2:
        type: string